### PR TITLE
Clear stream ref after stopped and extend returned props

### PR DESCRIPTION
**Pull request by sagodi97**
When using this library on a project I encountered the same (tiny) issues as described in #26 and #29.

I'm opening the PR out of concern for UX. Privacy is a sensitive issue, and as a user, I want to feel in control of when and why I'm sharing media with a site.

### CODE REVIEW

**Comment by Coelhomatias** [comment]
Hi @sagodi97, I tried your code and still get the same behavior, permissions are asked upon mount and not when I click startRecording. I installed via `npm install https://github.com/sagodi97/react-media-recorder.git`, don't know if it makes a difference. Do you know why I'm still getting the same behavior?

**Comment by sagodi97** [comment]
@Coelhomatias You're right, my PR partially addresses this. Since `audio:boolean` is a dependency of the `getMediaStream` method, you still need to do some tweaking on your side: Please see my answer here: **https://github.com/0x006F/react-media-recorder/issues/26#issuecomment-843032481**

**Comment by 0x006F** [comment]
Are you guys in for a `askPermissionsOnDemand` prop?

**Comment by sagodi97** [comment]
@0x006F Totally. Why as a prop though, shouldn't this be its default behavior?

**Comment by 0x006F** [comment]
Mainly, to ship this as a feature rather than a breaking change. 

> I want to feel in control of when and why I'm sharing media with a site.  

I totally get this, and I'm all in for better privacy. But from my pov, the user should be notified of possible certain device access in the current page. This might be incorrect, I'm not sure about that either. But like I said, main reason would be backward compatibility. 

Although, I don't see how "breaking" change this would be. 😕

**Comment by anvuongb** [comment]
> Are you guys in for a `askPermissionsOnDemand` prop?

Absolutely

**Comment by 0x006F** [comment]
@sagodi97 this is landed in the master through a different PR. If you're still around, can you verify this?

https://github.com/0x006F/react-media-recorder#askpermissiononmount

**Pull request closed without merging**
