### PR TITLE
feature(adds proper WAV codec support):

### PR DESCRIPTION
**Pull request by PipesNBottles**
- uses the extendable media recorder to allow use of WAV and other mime types
- fixes type issues where audio and video tags required undefined rather than null
- fixes issue where if mediaRecorderOptions are supplied the recorder stops recording after first audio blob recording

### CODE REVIEW

**Comment by PipesNBottles** [comment]
https://github.com/0x006F/react-media-recorder/issues/96#issue-1229011072
https://github.com/0x006F/react-media-recorder/issues/31#issue-750985683
solves these issues

**Comment by 0x006F** [comment]
Thanks a ton @PipesNBottles . If possible, could you remove the yarn lock as well? and update the version in 1.6.6

Much thanks!

**Comment by PipesNBottles** [comment]
the lock file has been removed and the version is updated!

**Comment by PipesNBottles** [comment]
I understand the concern, according to the creator of the external project his code sends the actual media stream to a web worker to convert it. 

https://stackoverflow.com/questions/65191193/media-recorder-save-in-wav-format-across-browsers

**Comment by seebham** [comment]
@PipesNBottles By any chance, does this fix #19?

**Pull request merged**
